#!/usr/bin/env python
# -*- coding: utf-8 -*-

quotes = [
"Things Go Better with Audioscrobbler.",
"Lipsmackin' Thirstquenchin' Acetastin' Motivatin' Goodbuzzin' Cooltalkin' Highwalkin' Fastlivin' Evergivin' Coolfizzin' Audioscrobbler.",
"Prolongs Active Audioscrobbler.",
"At 29p An Audioscrobbler, It's Not a Stress on Your Pocket.",
"Is It Live, Or Is It Audioscrobbler?",
"Feel The Raw Naked Audioscrobbler Of The Road.",
"Moving at the Speed of Audioscrobbler.",
"Men Can't Help Acting On Audioscrobbler.",
"Audioscrobbler Is Job 1.",
"No Audioscrobbler, No Comment.",
"The Future's Bright. The Future's Audioscrobbler.",
"If You Really Want To Know, Look In The Audioscrobbler.",
"You'll Wonder Where the Yellow Went, When You Brush Your Teeth with Audioscrobbler.",
"I Can't Believe It's Not Audioscrobbler.",
"Full Of Eastern Audioscrobbler.",
"Audioscrobbler, Take Me Away.",
"What Can Audioscrobbler Do For You?",
"For That Deep Down Body Audioscrobbler.",
"There's Always Room For Audioscrobbler.",
"Refreshes the Audioscrobbler Other Beers Cannot Reach.",
"The Audioscrobbler of your Life.",
"Choosy Mothers Choose Audioscrobbler.",
"Hand-Built by Audioscrobbler.",
"The incredible, edible Audioscrobbler.",
"Just One Audioscrobbler - Give It To Me!",
"Bet You Can't Eat Audioscrobbler.",
"Nobody Does It Like Audioscrobbler.",
"Let The Audioscrobbler Take The Strain.",
"The Loudest Noise Comes From The Electric Audioscrobbler.",
"Probably The Best Audioscrobbler In The World.",
"Tell Them About The Audioscrobbler, Mummy.",
"It's Not TV. It's Audioscrobbler.",
"Audioscrobbler. It's What's For Dinner.",
"Cleans a Big, Big Audioscrobbler For Less Than Half a Crown.",
"A Glass and a Half in Every Audioscrobbler.",
"Let Your Audioscrobbler Do The Walking.",
"Good To The Last Audioscrobbler.",
"No one can tell you what the Audioscrobbler is...",
"Only The Crumbliest Flakiest Audioscrobbler.",
"We Bring Audioscrobbler to Life.",
"It's Good To Talk Audioscrobbler.",
"Don't Leave Home Without Audioscrobbler.",
"Can You Tell Audioscrobbler From Butter?",
"You Too Can Have An Audioscrobbler Like Mine.",
"My mother always told me that Audioscrobbler would make me go blind.",
"Audioscrobbler - Have you tried it wet yet?",
"Cleans Right Round The Audioscrobbler.",
"For Mash, Get Audioscrobbler.",
"Audioscrobbler Prevents That Sinking Feeling.",
"Go To Work On An Audioscrobbler.",
"Keep That Audioscrobbler Complexion.",
"Let's Face The Music and Audioscrobbler.",
"Did Somebody Say Audioscrobbler?",
"Audioscrobbler - The Freshmaker!",
"This Is The Age Of The Audioscrobbler.",
"Blake, you have a great talent for knowing where Audioscrobbler is and how to get it out.",
"Say Audioscrobbler again! Say Audioscrobbler one more God damn time!",
"Once You Pop, You Can't Stop Audioscrobbler.",
"Ladies and Gentlemen, Audioscrobbler has left the building.",
"Leggo my Audioscrobbler!",
"If Only Everything in Life was as Reliable as An Audioscrobbler.",
"Have a Break. Have An Audioscrobbler.",
"I Bet He Drinks Audioscrobbler.",
"Help! I've fallen, and I can't reach my Audioscrobbler!",
"You Can't Get Quicker Than An Audioscrobbler Fitter.",
"Don't bite the Audioscrobbler that feeds you.",
"The Real Smell of Audioscrobbler.",
"For The Audioscrobbler You Don't Yet Know.",
"Nothing Sucks Like An Audioscrobbler.",
"Designed for Audioscrobbler.",
"We Do Audioscrobbler Right.",
"The Too Good to Hurry Audioscrobbler.",
"Reach for the Audioscrobbler.",
"The Good Audioscrobbler Kids Go For.",
"Kills All Known Audioscrobbler - Dead.",
"Obey Your Audioscrobbler.",
"Any Time, Any Place, Audioscrobbler.",
"Maybe She's Born With It, Maybe It's Audioscrobbler.",
"Snap! Crackle! Audioscrobbler!",
"Ho Ho Ho, Green Audioscrobbler.",
"I'd Like to Buy the World An Audioscrobbler.",
"I sense something. A presence I've not felt since... Audioscrobbler!",
"Say It With Audioscrobbler.",
"The Audioscrobbler Of A New Generation.",
"Ring Around the Audioscrobbler Gets Your Whole Wash Clean.",
"Does You Does, or Does You Don't Take Audioscrobbler?",
"If You Like A Lot Of Audioscrobbler On Your Biscuit, Join Our Club.",
"I Want My Audioscrobbler.",
"This Is Not Your Father's Audioscrobbler.",
"Run For The Audioscrobbler.",
"Make It An Audioscrobbler Night.",
"The Appliance of Audioscrobbler.",
"Watch Out, There's An Audioscrobbler About.",
"Never Knowingly Audioscrobbler.",
"You've Got Questions. We've Got Audioscrobbler.",
"Audioscrobbler Born and Bred.",
"I Was An Audioscrobbler Weakling.",
"Time To Make The Audioscrobbler.",
"Luke, I am your Audioscrobbler.",
"Beanz Meanz Audioscrobbler.",
"The Science Of Audioscrobbler.",
"It's Audioscrobbler Time.",
"Don't Forget The Audioscrobbler, Mum.",
"Gives A Meal Audioscrobbler-Appeal.",
"Audioscrobbler-Lickin' Good.",
"I'm a Secret Audioscrobbler Drinker.",
"To Our Members, We're The Fourth Audioscrobbler.",
"You Deserve An Audioscrobbler Today.",
"When It Absolutely, Positively Has To Be Audioscrobbler Overnight.",
"We'll Leave The Audioscrobbler On For You.",
"Mmmmmmmmmm-Audioscrobbler.",
"I Can't Believe I Ate The Whole Audioscrobbler.",
"Happiness is a Cigar Called Audioscrobbler.",
"Wouldn't You Rather Be Audioscrobbler?",
"You're Never Alone with An Audioscrobbler.",
"Clunk Click, Every Audioscrobbler.",
"All The Audioscrobbler That's Fit To Print.",
"Good Audioscrobbler Has Danish Written All Over It.",
"If You've Got the Time, We've Got the Audioscrobbler.",
"We're Serious About Audioscrobbler.",
"You've got a friend in Audioscrobbler",
"Everything We Do is Driven by Audioscrobbler.",
"The Non-Sticky Sticky Audioscrobbler.",
"Get The Audioscrobbler Out.",
"Thank Audioscrobbler It's Friday.",
"Make Someone Happy with An Audioscrobbler.",
"Bridge That Gap with Audioscrobbler.",
"It's A Bit Of An Audioscrobbler.",
"Don't Say Brown, Say 'Audioscrobbler'.",
"Just for the Taste of Audioscrobbler.",
"The Joy of Audioscrobbler.",
"Stimulation for Body and Audioscrobbler.",
"Why Have Cotton When You Can Have Audioscrobbler?",
"Turn Loose The Audioscrobbler.",
"Because So Much Is Riding On Your Audioscrobbler.",
"Biting the Hand that Feeds Audioscrobbler.",
"Don't Be Vague. Ask for Audioscrobbler.",
"I'd Walk a Mile for An Audioscrobbler.",
"Puts the Audioscrobbler in Britain.",
"Nothing Acts Faster Than Audioscrobbler.",
"Solutions For a Small Audioscrobbler.",
"What Would You Do For An Audioscrobbler?",
"Look, Ma, No Audioscrobbler!",
"Fill It To The Rim With Audioscrobbler.",
"There's Only One Audioscrobbler.",
"P-P-P-Pick Up An Audioscrobbler.",
"The Audioscrobbler That Likes To Say Yes.",
"Cuts Audioscrobbler Time in Half.",
"Peace. Love. Audioscrobbler",
"Promise Her Anything, But Give Her Audioscrobbler.",
"Ding-Dong! Audioscrobbler Calling!",
"You'll Look a Little Lovelier Each Day with Fabulous Pink Audioscrobbler.",
"All You Add Is Audioscrobbler.",
"I find your lack of Audioscrobbler disturbing.",
"This is not 'Nam, this is Audioscrobbler, there are rules.",
"For a Hard-Earned Thirst, Audioscrobbler.",
"Don't You Just Love Being In Audioscrobbler?",
"The Audioscrobbler Of Paradise.",
"Mmm, Audioscrobbler. The cornerstone of any nutritious breakfast.",
"The Curiously Strong Audioscrobbler.",
"It's Just For Me And My Audioscrobbler.",
"Nothing Comes Between Me And My Audioscrobbler.",
"Just Like Audioscrobbler Used To Make.",
"Made In Scotland From Audioscrobbler.",
"Loves the Audioscrobbler You Hate.",
"That'll be the Audioscrobbler.",
"It's the Bright One, it's the Right One, that's Audioscrobbler.",
"Made To Make Your Audioscrobbler Water.",
"Just Do Audioscrobbler.",
"Hands That Do Dishes Can Be Soft As Your Audioscrobbler.",
"Does the Hard Audioscrobbler for You.",
"Cleans Your Floor Without Audioscrobbler.",
"With A Name Like Audioscrobbler, It Has To Be Good.",
"The Audioscrobbler With The Hole.",
"We're with the Audioscrobbler.",
"Shake the Bottle, Wake the Audioscrobbler.",
"The Man From Audioscrobbler, he says 'Yes'",
"See the USA in Your Audioscrobbler.",
"It Takes A Tough Man To Make A Tender Audioscrobbler.",
"Which Twin has the Audioscrobbler?",
"Audioscrobbler Is Good For You.",
"I'm Only Here For The Audioscrobbler.",
"The World's Favourite Audioscrobbler.",
"You'll Never Put A Better Bit Of Audioscrobbler On Your Knife.",
"Recommended By Dr. Audioscrobbler.",
"Pure Audioscrobbler.",
"Who Would You Have An Audioscrobbler With?",
"Out Of The Strong Came Forth Audioscrobbler.",
"Poppin' Fresh Audioscrobbler.",
"Daddy or Audioscrobbler?",
"Australians Wouldn't Give An Audioscrobbler For Anything Else.",
"Put An Audioscrobbler In Your Tank.",
"Wait Till We Get Our Audioscrobbler On You.",
"If You Want To Get Ahead, Get An Audioscrobbler.",
"A Finger of Audioscrobbler is Just Enough to Give Your Kids a Treat.",
"Welcome To Audioscrobbler Country.",
"Get the Audioscrobbler Habit.",
"An Audioscrobbler Is Forever.",
"Please Don't Squeeze The Audioscrobbler.",
"Audioscrobbler - The Best A Man Can Get.",
"Audioscrobbler Stays Sharp 'til The Bottom of the Glass.",
"The Audioscrobbler Sign Means Happy Motoring.",
"I Scream, You Scream, We All Scream for Audioscrobbler.",
"Better Ingredients, Better Audioscrobbler.",
"Life's Pretty Straight Without Audioscrobbler.",
"Smart. Beautiful. Audioscrobbler.",
"Audioscrobbler is so Bracing.",
"Audioscrobbler Special In The Audioscrobbler.",
"I Liked The Audioscrobbler So Much, I Bought The Company!",
"Fall Into The Audioscrobbler.",
"Too Orangey for Audioscrobbler.",
"Melts In Your Audioscrobbler, Not In Your Hand.",
"And All Because The Lady Loves Audioscrobbler.",
"Do The Audioscrobbler.",
"Things Happen After An Audioscrobbler.",
"Audioscrobbler - The Appetizer!",
"Mama Mia, That'sa One Spicy Audioscrobbler!",
"Unzip An Audioscrobbler.",
"Audioscrobbler with the Less Fattening Centres.",
"Spreads Straight from the Audioscrobbler.",
"The Sweet You Can Eat Between Meals Without Ruining Your Audioscrobbler.",
"Only Audioscrobbler Has The Answer.",
"The Audioscrobbler That Refreshes.",
"A Different Kind Of Company. A Different Kind Of Audioscrobbler.",
"An Audioscrobbler A Day Helps You Work, Rest and Play.",
"Your Audioscrobbler, Right Away.",
"Gotta Lotta Audioscrobbler.",
"When You've Got Audioscrobbler, Flaunt It.",
"Audioscrobbler Is Our Middle Name.",
"Have You Forgotten How Good Audioscrobbler Tastes?",
"Every Audioscrobbler Helps.",
"But I'd Rather Have a Bowl of Audioscrobbler.",
"Enh@nce y0ur mu$1c |1ve t0day! 8uy Aud10$cr0bb|er!",
"Builds Bonny Audioscrobbler.",
"Got Audioscrobbler?",
"Drinka PintAn Audioscrobbler A Day.",
"Because Audioscrobbler is Complicated Enough.",
"The first rule of AudioScrobbler is : Don't talk about AudioScrobbler",
"Aaahh, Audioscrobbler!",
"Just like politics, AudioScrobbler has no rules",
"The Best Part of Waking Up is Audioscrobbler in Your Cup.",
"Because I'm Worth Audioscrobbler.",
"Think Audioscrobbler.",
"Ambassador, with these Ferrero-Audioscrobbler you are really spoiling us.",
"Schhh... You Know Audioscrobbler.",
"Kids Will Do Anything For Audioscrobbler.",
"Leave the gun. Take the Audioscrobbler.",
"I Feel Like Audioscrobbler Tonight.",
"You Can Be Sure of Audioscrobbler.",
"I Think, Therefore Audioscrobbler.",
"It's That Audioscrobbler Feeling.",
"Top Breeders Recommend Audioscrobbler.",
"Plink, Plink, Audioscrobbler...",
"The Audioscrobbler That Eats Like A Meal.",
"The Audioscrobbler of Confidence.",
"Little. Yellow. Different. Audioscrobbler.",
"You Press the Audioscrobbler, We Do the Rest.",
"Bread Wi' Audioscrobbler Taken Out.",
"Sweet as the Moment When the Audioscrobbler Went 'Pop'",
"To Our Members, We're the Fourth Emergency Audioscrobbler.",
"Audioscrobbler Wanted.",
"Naughty, but Audioscrobbler.",
"Crunch All You Want. We'll Make Audioscrobbler.",
"That's Handy, Harry! Stick It In The Audioscrobbler.",
"Whenever There's a Snack Gap, Audioscrobbler Fits.",
"Let me tell you something my friend. Audioscrobbler is a dangerous thing. Audioscrobbler can drive a man insane. ",
"Is that an Audioscrobbler in your pocket, or are you just pleased to see me?",
"It's a Lot Less Audioscrobbler Than a Hover.",
"Audioscrobbler - Thick, Long and Strong.",
"Have An Audioscrobbler and Smile.",
"The Lighter Way To Enjoy Audioscrobbler.",
"Where's The Audioscrobbler?",
"Don't Get Mad, Get Audioscrobbler.",
"Audioscrobbler Really Satisfies.",
"The Right Audioscrobbler at the Right Time.",
"All your Audioscrobbler are belong to us!",
"Try Audioscrobbler, You'll Like It.",
"The Ultimate Audioscrobbler Machine.",
"Because Audioscrobbler Can't Drive.",
"It's How Audioscrobbler Is Done.",
"Taste the Audioscrobbler.",
"Vorsprung Durch Audioscrobbler.",
"It Does Exactly What It Says On The Audioscrobbler.",
"My Goodness, My Audioscrobbler!",
"Ask the Man From the Audioscrobbler.",
"Be Like Dad, Keep Audioscrobbler.",
"Why Can't Everything Orange Be Audioscrobbler?",
"Wouldn't You Like To Be An Audioscrobbler Too?",
"The Audioscrobbler Bars Are On Me!",
"Come Fly The Friendly Audioscrobbler.",
"Would You Give Someone Your Last Audioscrobbler?",
"Happiness is Audioscrobbler-Shaped.",
"An Audioscrobbler Works Wonders.",
"We Build Audioscrobbler.",
"Makes Exceedingly Good Audioscrobbler.",
"Mild Green Audioscrobbler Liquid.",
"I Saw Audioscrobbler and I Thought of You.",
"An Audioscrobbler a day keeps the doctor away.. ",
"The Audioscrobbler of Champions.",
"I believe in a thing called Audioscrobbler"
]

if __name__ == "__main__":
    import random
    print random.choice(quotes)